export const IA_IMAGES = [
  {
    title: 'Bugs with Dua Lipa',
    data: [
      'https://love-chi-six.vercel.app/ia/broken1.png',
      'https://love-chi-six.vercel.app/ia/broken2.png',
    ],
  },
  {
    title: 'Grrrr Sexy',
    data: [
      'https://love-chi-six.vercel.app/ia/grr1.png',
      'https://love-chi-six.vercel.app/ia/grr2.png',
      'https://love-chi-six.vercel.app/ia/grr3.png',
      'https://love-chi-six.vercel.app/ia/grr4.png',
      'https://love-chi-six.vercel.app/ia/grr5.png',
      'https://love-chi-six.vercel.app/ia/grr6.png',
      'https://love-chi-six.vercel.app/ia/grr7.png',
      'https://love-chi-six.vercel.app/ia/grr8.png',
      'https://love-chi-six.vercel.app/ia/grr9.png',
      'https://love-chi-six.vercel.app/ia/grr10.png',
      'https://love-chi-six.vercel.app/ia/grr11.png',
      'https://love-chi-six.vercel.app/ia/grr12.png',
    ],
  },
  {
    title: 'James Webb space telescope black hole',
    data: ['https://love-chi-six.vercel.app/ia/hole.png'],
  },
  {
    title: 'Que miras? Te gusto?',
    data: [
      'https://love-chi-six.vercel.app/ia/judgmental1.png',
      'https://love-chi-six.vercel.app/ia/judgmental2.png',
      'https://love-chi-six.vercel.app/ia/judgmental3.png',
      'https://love-chi-six.vercel.app/ia/judgmental4.png',
      'https://love-chi-six.vercel.app/ia/judgmental5.png',
      'https://love-chi-six.vercel.app/ia/judgmental6.png',
      'https://love-chi-six.vercel.app/ia/judgmental7.png',
      'https://love-chi-six.vercel.app/ia/judgmental8.png',
    ],
  },
  {
    title: 'Lovers',
    data: [
      'https://love-chi-six.vercel.app/ia/lovers1.png',
      'https://love-chi-six.vercel.app/ia/lovers2.png',
      'https://love-chi-six.vercel.app/ia/lovers3.png',
      'https://love-chi-six.vercel.app/ia/lovers4.png',
      'https://love-chi-six.vercel.app/ia/lovers5.png',
      'https://love-chi-six.vercel.app/ia/lovers6.png',
      'https://love-chi-six.vercel.app/ia/lovers7.png',
    ],
  },
  {
    title: 'I am fine',
    data: [
      'https://love-chi-six.vercel.app/ia/ok1.png',
      'https://love-chi-six.vercel.app/ia/ok2.png',
      'https://love-chi-six.vercel.app/ia/ok3.png',
      'https://love-chi-six.vercel.app/ia/ok4.png',
      'https://love-chi-six.vercel.app/ia/ok5.png',
    ],
  },
  {
    title: 'I am not fine',
    data: [
      'https://love-chi-six.vercel.app/ia/party1.png',
      'https://love-chi-six.vercel.app/ia/party2.png',
      'https://love-chi-six.vercel.app/ia/party3.png',
      'https://love-chi-six.vercel.app/ia/party4.png',
      'https://love-chi-six.vercel.app/ia/party5.png',
      'https://love-chi-six.vercel.app/ia/party6.png',
      'https://love-chi-six.vercel.app/ia/party7.png',
      'https://love-chi-six.vercel.app/ia/party8.png',
      'https://love-chi-six.vercel.app/ia/party9.png',
      'https://love-chi-six.vercel.app/ia/party10.png',
      'https://love-chi-six.vercel.app/ia/party11.png',
      'https://love-chi-six.vercel.app/ia/party12.png',
    ],
  },
  {
    title: 'Robocop',
    data: [
      'https://love-chi-six.vercel.app/ia/robot1.png',
      'https://love-chi-six.vercel.app/ia/robot2.png',
    ],
  },
  {
    title: 'DNI Photo',
    data: [
      'https://love-chi-six.vercel.app/ia/serious1.png',
      'https://love-chi-six.vercel.app/ia/serious2.png',
      'https://love-chi-six.vercel.app/ia/serious3.png',
      'https://love-chi-six.vercel.app/ia/serious4.png',
      'https://love-chi-six.vercel.app/ia/serious5.png',
      'https://love-chi-six.vercel.app/ia/serious6.png',
      'https://love-chi-six.vercel.app/ia/serious7.png',
      'https://love-chi-six.vercel.app/ia/serious8.png',
      'https://love-chi-six.vercel.app/ia/serious9.png',
      'https://love-chi-six.vercel.app/ia/serious10.png',
    ],
  },
  {
    title: 'Stalker POV',
    data: [
      'https://love-chi-six.vercel.app/ia/stalker1.png',
      'https://love-chi-six.vercel.app/ia/stalker2.png',
      'https://love-chi-six.vercel.app/ia/stalker3.png',
      'https://love-chi-six.vercel.app/ia/stalker4.png',
    ],
  },
  {
    title: 'Modelo Sof-IA',
    data: [
      'https://love-chi-six.vercel.app/ia/model1.png',
      'https://love-chi-six.vercel.app/ia/model2.png',
      'https://love-chi-six.vercel.app/ia/model3.png',
      'https://love-chi-six.vercel.app/ia/model4.png',
      'https://love-chi-six.vercel.app/ia/model5.png',
      'https://love-chi-six.vercel.app/ia/model6.png',
      'https://love-chi-six.vercel.app/ia/model7.png',
      'https://love-chi-six.vercel.app/ia/model8.png',
      'https://love-chi-six.vercel.app/ia/model9.png',
      'https://love-chi-six.vercel.app/ia/model10.png',
      'https://love-chi-six.vercel.app/ia/model11.png',
      'https://love-chi-six.vercel.app/ia/model12.png',
      'https://love-chi-six.vercel.app/ia/model13.png',
      'https://love-chi-six.vercel.app/ia/model14.png',
    ],
  },
];
